import { EventItem, PackageItem, TestimonialItem } from './types';

export const EVENTS_DATA: EventItem[] = [
  {
    id: 'africatech-2025',
    title: 'Silicon Valley Tech Summit 2025',
    date: 'Oct 12, 2025',
    fullDate: 'Saturday, October 12, 2025',
    venue: 'Moscone Center',
    city: 'San Francisco',
    price: 450,
    formattedPrice: '$450',
    organizer: 'Presented by Silicon Valley Tech Media',
    isFeatured: true,
    description: 'Silicon Valley Tech Summit 2025 brings together tech leaders, ecosystem builders, corporates, international investors, and startups from across the country. The summit delivers unmatched opportunities to connect, network, and co-create future solutions. Over two intensive days, we explore the frontiers of fintech, artificial intelligence, climate technology, and scaling across global borders.\n\nDelve deep into curated panels, masterclasses, and executive fireside chats led by visionary founders. Discover cutting-edge technological advancements, build valuable cross-border partnerships, and gain practical insights from leaders shaping the digital ecosystem of tomorrow.\n\nHosted at the prestigious Moscone Center in downtown San Francisco, the summit features double-track speaker stages, exclusive networking lounges, and interactive product demo showcases. Secure your seat today to be part of the nation\'s primary digital transformation dialogue.',
    imageUrl: 'https://i.pinimg.com/1200x/c3/20/7d/c3207d2f303de1de4bf2a14fcb76bd10.jpg',
  },
  {
    id: 'sundowner-sessions',
    title: 'Sunset Rooftop Sessions',
    date: 'Oct 18, 2025',
    fullDate: 'Friday, October 18, 2025',
    venue: 'Aloft Hotel, Rooftop Lounge',
    city: 'Los Angeles',
    price: 45,
    formattedPrice: '$45',
    organizer: 'Presented by LA House Collective',
    isFeatured: false,
    description: 'A premium electronic, deep house, and indie dance night featuring guest selectors from across the globe. Join us high above the Los Angeles skyline as the sun dips below the horizon, bathing the rooftop in golden hues. This is an intimate gathering for true audiophiles and connoisseurs of deep rhythms.\n\nEnjoy hand-crafted herbal cocktails, curated small plates, and custom visual projections paired perfectly with premium ambient and rhythmic progressions. Dress code is high-end minimalism.',
    imageUrl: 'https://i.pinimg.com/1200x/79/30/0c/79300ceec670c8b6f122acca7dcc2b9c.jpg',
  },
  {
    id: 'food-festival',
    title: 'Pacific Coast Food Festival',
    date: 'Oct 25, 2025',
    fullDate: 'Saturday, October 25, 2025',
    venue: 'Santa Monica Waterfront',
    city: 'Los Angeles',
    price: 'FREE',
    formattedPrice: 'FREE',
    organizer: 'Presented by West Coast Cuisines',
    isFeatured: false,
    description: 'A grand celebration of coastal, regional, and national culinary arts situated on the ocean breeze at Santa Monica Waterfront. Taste your way through over forty curated artisan booths showcasing authentic coastal street foods, contemporary fusion cuisines, and masterclasses from award-winning regional chefs.\n\nExperience live acoustic stages, interactive mocktail mixology workshops, and organic fresh-produce markets. Admission is completely complimentary, but reservations are mandatory to regulate access.',
    imageUrl: 'https://i.pinimg.com/736x/94/fb/94/94fb944160b705d86d10595b469d7a82.jpg',
  },
  {
    id: 'growth-marketing',
    title: 'Growth Marketing Masterclass',
    date: 'Nov 2, 2025',
    fullDate: 'Sunday, November 2, 2025',
    venue: 'The Metreon, SoMa',
    city: 'San Francisco',
    price: 150,
    formattedPrice: '$150',
    organizer: 'Presented by GrowthX US',
    isTrending: true,
    description: 'Unlocking the exact playbook for scaling modern digital consumer products across North American and global markets. This highly hands-on technical session details customer acquisition strategies, retention loops, performance marketing budget optimization, and utilizing zero-party data.\n\nParticipants will analyze real regional case studies and build their own custom growth models. Strictly limited to fifty selected executives and high-potential marketing leaders.',
    imageUrl: 'https://i.pinimg.com/1200x/9d/1e/07/9d1e0795ab13c08779293f2eed437777.jpg',
  },
  {
    id: 'blankets-wine',
    title: 'Napa Wine & Music Festival',
    date: 'Nov 8, 2025',
    fullDate: 'Sunday, November 8, 2025',
    venue: 'Laureat Gardens',
    city: 'Napa Valley',
    price: 120,
    formattedPrice: '$120',
    organizer: 'Presented by Wine Country Entertainment',
    isTrending: true,
    description: 'The iconic cultural showcase highlighting pioneering music, fashion, and contemporary arts. Bringing a carefully curated lineup of live alternative acts, acoustic ensembles, and legendary selectors to the beautiful grasslands of Laureat Gardens in Napa Valley.\n\nBring your customized picnic spreads, blankets, and expressive fashion ensembles. Secure your placement and join Napa\'s premier lifestyle and live music community event.',
    imageUrl: 'https://i.pinimg.com/1200x/65/09/22/650922e836ba0684e95af4b52561f96f.jpg',
  },
  {
    id: 'fashion-week',
    title: 'New York Fashion Week',
    date: 'Nov 15, 2025',
    fullDate: 'Saturday, November 15, 2025',
    venue: 'The Shed, Hudson Yards',
    city: 'New York',
    price: 250,
    formattedPrice: '$250',
    organizer: 'Presented by Gotham Fashion Guild',
    isTrending: true,
    description: 'Witness the future of fashion design as New York Fashion Week returns under the theme "Sustainable Textiles & Avant-Garde Luxury." Showcasing premier collections from twelve radical couturiers and textile pioneers representing New York, Paris, and Milan.\n\nEnjoy VIP seating options, live performance intervals, and immediate access to the exclusive ready-to-wear runway retail trunk show.',
    imageUrl: 'https://i.pinimg.com/1200x/ab/e4/54/abe454ed634ef4ec4bf3f55d00524ed1.jpg',
  },
  {
    id: 'startup-funding',
    title: 'SaaS Funding Bootcamp',
    date: 'Nov 20, 2025',
    fullDate: 'Thursday, November 20, 2025',
    venue: 'WeWork Broadway, Manhattan',
    city: 'New York',
    price: 99,
    formattedPrice: '$99',
    organizer: 'Presented by Founders Network US',
    isTrending: true,
    description: 'An intensive, no-nonsense workshop for early-stage founders seeking to raise Seed and Series A financing. Led by active managing partners of regional VC funds and successful serial entrepreneurs who have raised over $100M collectively.\n\nWalk away with templates for your pitch decks, financial projection models, cap tables, and legal term sheet checklists. Pitch feedback clinics are included in the ticket registration.',
    imageUrl: 'https://i.pinimg.com/736x/d0/ce/16/d0ce165ec33f58775dfa5ce61f4f9c0.jpg',
  },
  {
    id: 'champions-league',
    title: 'Champions League Watch Party',
    date: 'Nov 26, 2025',
    fullDate: 'Wednesday, November 26, 2025',
    venue: 'The Playwright Sports Lounge',
    city: 'New York',
    price: 25,
    formattedPrice: '$25',
    organizer: 'Presented by SportsZone New York',
    isTrending: true,
    description: 'Experience the pinnacle of European club football on massive high-definition screens surrounded by ultra-premium spatial audio. Featuring live tactical commentary, score prediction games with high-end prizes, and dynamic pre-match debate sessions led by top sports journalists.\n\nTicket entry includes a complimentary custom craft beer or mocktail and premium gastro-pub appetizers.',
    imageUrl: 'https://i.pinimg.com/736x/37/45/34/3745341c6051dcf60de95589f7edd3e6.jpg',
  },
  {
    id: 'family-fun-expo',
    title: 'Family Fun Day Expo',
    date: 'Nov 22, 2025',
    fullDate: 'Saturday, November 22, 2025',
    venue: 'Central Park Great Lawn',
    city: 'New York',
    price: 'FREE',
    formattedPrice: 'FREE',
    organizer: 'Presented by Manhattan Community Board',
    description: 'An expansive weekend festival overlooking the greenery of Central Park, built entirely for creating beautiful multi-generational memories. Featuring interactive children\'s STEAM discovery zones, gourmet family-style outdoor food stalls, dynamic live puppetry, and classical regional orchestral showcases.\n\nRegister in advance to receive custom priority entry vouchers and secure family workshop seat assignments.',
    imageUrl: 'https://i.pinimg.com/1200x/43/17/14/431714b2cee15ce7fc11a08c540b96b6.jpg',
  },
  {
    id: 'jazz-champagne-soiree',
    title: 'Jazz & Champagne Soirée',
    date: 'Nov 29, 2025',
    fullDate: 'Saturday, November 29, 2025',
    venue: 'The Blue Note, Greenwich Village',
    city: 'New York',
    price: 95,
    formattedPrice: '$95',
    organizer: 'Presented by Greenwich Jazz Association',
    isTrending: true,
    description: 'An evening of smooth contemporary jazz accompanied by premium champagnes and exquisite hors d\'oeuvres. Relax in our dimly lit parlor as international and local instrumentalists collaborate on timeless standards and modern interpretations.',
    imageUrl: 'https://i.pinimg.com/1200x/c7/2e/7c/c72e7c451c58d102c4247a107354be90.jpg',
  },
  {
    id: 'modern-art-gala',
    title: 'Modern Art Gala',
    date: 'Dec 4, 2025',
    fullDate: 'Thursday, December 4, 2025',
    venue: 'The Glass House Gallery',
    city: 'New York',
    price: 150,
    formattedPrice: '$150',
    organizer: 'Presented by Contemporary Art Society NY',
    isFeatured: true,
    description: 'A prestigious annual gala showcasing avant-garde paintings, sculptural installations, and performance art from the nation\'s most daring creators. Network with collectors, curators, and cultural visionaries under dramatic lighting and custom soundscapes.',
    imageUrl: 'https://i.pinimg.com/1200x/60/6f/d5/606fd57f29aef577600b98183d5fd3fe.jpg',
  },
  {
    id: 'symphony-under-stars',
    title: 'Symphony Under the Stars',
    date: 'Dec 6, 2025',
    fullDate: 'Saturday, December 6, 2025',
    venue: 'Hollywood Bowl Amphitheatre',
    city: 'Los Angeles',
    price: 85,
    formattedPrice: '$85',
    organizer: 'Presented by Los Angeles Philharmonic',
    description: 'Experience the sweeping sounds of a live 60-piece orchestra playing under a clear night sky. Bringing classical masterpieces and cinematic scores to life amidst the natural acoustics of the Hollywood Bowl. Bring your own cushions and picnic baskets.',
    imageUrl: 'https://i.pinimg.com/1200x/63/1b/1b/631b1b64f8214fef3c1754d1540cdaad.jpg',
  },
  {
    id: 'solstice-soundclash',
    title: 'The Solstice Soundclash',
    date: 'Dec 12, 2025',
    fullDate: 'Friday, December 12, 2025',
    venue: 'The Brooklyn Warehouse',
    city: 'New York',
    price: 35,
    formattedPrice: '$35',
    organizer: 'Presented by Sound System US',
    isTrending: true,
    description: 'A legendary night celebrating heavy bass, reggae, dub, and electronic soundscapes. Featuring a towering custom sound system and top-tier selectas spinning rare vinyl records and exclusive remixes. Immerse yourself in the ultimate sub-bass frequency experience.',
    imageUrl: 'https://i.pinimg.com/736x/da/65/b7/da65b7f0cbbc42c036bb041f7622a997.jpg',
  },
  {
    id: 'whisky-cigar-masterclass',
    title: 'Whisky & Cigar Masterclass',
    date: 'Dec 17, 2025',
    fullDate: 'Wednesday, December 17, 2025',
    venue: 'The Oak Room, Manhattan',
    city: 'New York',
    price: 125,
    formattedPrice: '$125',
    organizer: 'Presented by Single Malt Society US',
    description: 'An ultra-exclusive tasting journey pairing rare single malt whiskies with hand-rolled cigars. Led by a certified master sommelier, participants will learn the fine art of flavor profiling, history, and optimal aging techniques in an intimate club environment.',
    imageUrl: 'https://i.pinimg.com/736x/08/22/b9/0822b9196846daa7362e93fc298c7e47.jpg',
  },
  {
    id: 'chocolatier-pastry-exhibition',
    title: 'Chocolatier & Pastry Exhibition',
    date: 'Dec 20, 2025',
    fullDate: 'Saturday, December 20, 2025',
    venue: 'The Plaza Hotel Ballrooms',
    city: 'New York',
    price: 75,
    formattedPrice: '$75',
    organizer: 'Presented by Artisan Bakers Guild US',
    description: 'A delightful exhibition of gourmet chocolates, delicate pastries, and masterful sugar sculptures. Watch live demonstrations by award-winning pastry chefs and taste a wide variety of artisanal treats infused with regional organic ingredients.',
    imageUrl: 'https://i.pinimg.com/1200x/f1/e7/8d/f1e78d2d6ad49fe23a16bef8ce668885.jpg',
  },
  {
    id: 'minimalist-design-expo',
    title: 'Minimalist Design Expo',
    date: 'Dec 28, 2025',
    fullDate: 'Sunday, December 28, 2025',
    venue: 'The Shift Design Gallery',
    city: 'Chicago',
    price: 40,
    formattedPrice: '$40',
    organizer: 'Presented by Design Studio Chicago',
    description: 'Discover the beauty of form, function, and negative space. This expo features contemporary furniture, architectural blueprints, and sustainable spatial designs from cutting-edge designers across the country. Meet the minds behind the region\'s modernist renaissance.',
    imageUrl: 'https://i.pinimg.com/236x/fc/43/c0/fc43c0fe7311e54caa2fc12016d1606d.jpg',
  },
  {
    id: 'sunset-yacht-cruise',
    title: 'Sunset Yacht Cruise',
    date: 'Jan 3, 2026',
    fullDate: 'Saturday, January 3, 2026',
    venue: 'Miami Beach Marina',
    city: 'Miami',
    price: 175,
    formattedPrice: '$175',
    organizer: 'Presented by Miami Yacht Charters',
    isFeatured: true,
    description: 'An unforgettable premium cruise along the beautiful coast of Miami Beach. Enjoy gourmet coastal seafood bites, fresh tropical mocktails, and live acoustic ambient melodies as the golden sun dips into the Atlantic Ocean. Strictly limited boarding slots.',
    imageUrl: 'https://i.pinimg.com/1200x/a9/41/3e/a9413e56fb2e0848c4b0410aad2da45c.jpg',
  },
  {
    id: 'retro-vinyl-funk-night',
    title: 'Retro Vinyl & Funk Night',
    date: 'Jan 9, 2026',
    fullDate: 'Friday, January 9, 2026',
    venue: 'The Muze Bar, Brooklyn',
    city: 'New York',
    price: 30,
    formattedPrice: '$30',
    organizer: 'Presented by Vinyl Collective NYC',
    isTrending: true,
    description: 'Step back in time with an all-vinyl DJ set celebrating the golden eras of funk, soul, disco, and early Motown. Dance to warm analog sounds, rare grooves, and custom vintage-inspired visual projections under ambient retro lighting.',
    imageUrl: 'https://i.pinimg.com/736x/ab/bd/73/abbd73bbd16fbec71ffdf67b1cb025bf.jpg',
  },
  {
    id: 'coastal-seafood-festival',
    title: 'Coastal Seafood Festival',
    date: 'Jan 18, 2026',
    fullDate: 'Sunday, January 18, 2026',
    venue: 'South Beach Oceanfront',
    city: 'Miami',
    price: 65,
    formattedPrice: '$65',
    organizer: 'Presented by South Beach Culinary Club',
    description: 'A beachfront culinary spectacle celebrating the freshest catch of the day. Sample giant prawns, lobster tail, charcoal-grilled snapper, and authentic key lime treats prepared by local masters. Enjoy live local bands on the white sands.',
    imageUrl: 'https://i.pinimg.com/1200x/ef/a3/47/efa347ef717105aa135a57271cd70d9e.jpg',
  },
  {
    id: 'seattle-coffee-cupping',
    title: 'Specialty Coffee Cupping',
    date: 'Jan 24, 2026',
    fullDate: 'Saturday, January 24, 2026',
    venue: 'The Coffee Lab, Capital Hill',
    city: 'Seattle',
    price: 45,
    formattedPrice: '$45',
    organizer: 'Presented by Specialty Coffee Association',
    description: 'An aromatic tasting and evaluation workshop exploring high-grade Arabica beans from different micro-climates. Learn standard SCA cupping protocols, fragrance-to-aroma transitions, and perfect brewing temperatures.',
    imageUrl: 'https://i.pinimg.com/736x/86/6e/3c/866e3cccf297bcfb9659bf5ba916a2c1.jpg',
  },
  {
    id: 'acoustic-forest-sessions',
    title: 'Acoustic Redwood Sessions',
    date: 'Jan 31, 2026',
    fullDate: 'Saturday, January 31, 2026',
    venue: 'Muir Woods Sanctuary',
    city: 'San Francisco',
    price: 60,
    formattedPrice: '$60',
    organizer: 'Presented by Acoustic California',
    isFeatured: true,
    description: 'A highly intimate unplugged live performance featuring award-winning alternative singer-songwriters. Nestled in a secluded redwood clearing of Muir Woods with simple warm fairy lighting, offering an organic and deeply personal connection with the music.',
    imageUrl: 'https://i.pinimg.com/736x/bf/90/c2/bf90c2b6cc3b24be0c872e825c59e380.jpg',
  },
  {
    id: 'lake-victoria-sunset-regatta',
    title: 'Lake Michigan Sunset Regatta',
    date: 'Feb 7, 2026',
    fullDate: 'Saturday, February 7, 2026',
    venue: 'Chicago Yacht Club',
    city: 'Chicago',
    price: 'FREE',
    formattedPrice: 'FREE',
    organizer: 'Presented by Great Lakes Tourism Board',
    description: 'A vibrant sailboat regatta showcasing stunning sails and competitive racing along the waters of Lake Michigan. Watch from the grassy club lawns, enjoy local fish fry stalls, live music, and a spectacular sunset over the lake.',
    imageUrl: 'https://i.pinimg.com/736x/78/b2/58/78b258df8d2f5bbc7ec5303bbb0ba75c.jpg',
  },
  {
    id: 'tech-venture-gala',
    title: 'Tech Venture Gala',
    date: 'Feb 12, 2026',
    fullDate: 'Thursday, February 12, 2026',
    venue: 'The Four Seasons, East Palo Alto',
    city: 'Palo Alto',
    price: 150,
    formattedPrice: '$150',
    organizer: 'Presented by Silicon Valley Capital Partners',
    isTrending: true,
    description: 'An elite networking evening connecting high-potential tech founders with venture capital partners and angel investors. Enjoy curated pitches, structured speed-networking, panel discussions on regional trends, and a gourmet three-course dinner.',
    imageUrl: 'https://i.pinimg.com/1200x/90/7e/7d/907e7d060e7408ed7dcce2c4eab50699.jpg',
  },
  {
    id: 'modernist-furniture-showcase',
    title: 'Modernist Furniture Showcase',
    date: 'Feb 15, 2026',
    fullDate: 'Sunday, February 15, 2026',
    venue: 'Design District Gallery',
    city: 'Los Angeles',
    price: 35,
    formattedPrice: '$35',
    organizer: 'Presented by Craft & Wood West Coast',
    description: 'An exclusive exhibition of premium, minimalist indoor and outdoor furniture designed using sustainably-sourced hardwoods. Highlighting the harmony between raw natural elements and sleek, contemporary structural geometry.',
    imageUrl: 'https://i.pinimg.com/1200x/96/ec/6d/96ec6d7945cec81cc913a9d5fd8c6dcc.jpg',
  },
  {
    id: 'street-style-runway',
    title: 'Street Style Runway',
    date: 'Feb 21, 2026',
    fullDate: 'Saturday, February 21, 2026',
    venue: 'The Wynwood Yards',
    city: 'Miami',
    price: 55,
    formattedPrice: '$55',
    organizer: 'Presented by Streetwear Coalition US',
    isFeatured: true,
    description: 'A high-octane outdoor runway highlighting the raw energy of urban fashion and local streetwear brands. Watch models strut through repurposed industrial spaces, accompanied by underground hip-hop selectors, live graffiti murals, and pop-up retail booths.',
    imageUrl: 'https://i.pinimg.com/1200x/95/50/16/9550166f9b5990397aebc5339255ce25.jpg',
  }
];

export const PACKAGES_DATA: PackageItem[] = [
  {
    id: 'basic',
    name: 'BASIC',
    priceText: '$25',
    priceVal: 25,
    description: '7-day listing, standard platform placement.',
    features: [
      'Verified listing on active discovery lists',
      'Included in regional city filters',
      'Social sharing shareable links generated',
      'Basic analytics dashboard access'
    ]
  },
  {
    id: 'featured',
    name: 'FEATURED',
    priceText: '$65',
    priceVal: 65,
    isPopular: true,
    description: '14-day listing, homepage featured card, email newsletter mention.',
    features: [
      'Everything in Basic tier included',
      'Homepage Featured row placement',
      'Dedicated premium boost (top of lists)',
      'Mentions in weekly email newsletters',
      'Extended performance analytics report'
    ]
  },
  {
    id: 'spotlight',
    name: 'SPOTLIGHT',
    priceText: '$120',
    priceVal: 120,
    description: '21-day listing, homepage featured, email blast, social media posts (3 platforms).',
    features: [
      'Everything in Featured tier included',
      'Continuous Hero Ticker marquee listing',
      'Direct solus email blast to subscribers',
      'Tailored Instagram & TikTok promotional video reels',
      'Guaranteed attendee turnout consultation'
    ]
  },
  {
    id: 'social-boost',
    name: 'SOCIAL BOOST',
    priceText: '$30',
    priceVal: 30,
    isAddon: true,
    description: 'Instagram + TikTok posts only. Combinable with any package.',
    features: [
      'Express custom visual template asset generation',
      'Instagram Story slide listing with direct swipe link',
      'TikTok short-form mention on weekly top event guides'
    ]
  }
];

export const TESTIMONIALS_DATA: TestimonialItem[] = [
  {
    id: 't1',
    initials: 'JA',
    quote: 'VELUX is quite literally the only promotional channel that delivers high-intent patrons to our masterclasses. We sold out in forty-eight hours.',
    author: 'Joy Adams',
    role: 'Founder, GrowthX US'
  },
  {
    id: 't2',
    initials: 'SE',
    quote: 'Selling premium electronic music experiences requires reaching an audience that understands editorial quality. VELUX commands that audience perfectly.',
    author: 'Sasha Evans',
    role: 'Lead Curator, House Nation LA'
  },
  {
    id: 't3',
    initials: 'AM',
    quote: 'The return on ad spend was completely unmatched. Over ninety percent of our VIP ticket holders cited VELUX as their discovery source.',
    author: 'Arthur Miller',
    role: 'Creative Director, Gotham Fashion Guild'
  }
];

export const AGENDA_DATA = [
  {
    time: '08:00 AM — 09:30 AM',
    title: 'Registration & Morning Pour Over',
    speaker: 'Aroma Espresso Lounge & Networking Lobby'
  },
  {
    time: '09:30 AM — 11:00 AM',
    title: 'Opening Keynote: Scaling Across Borders',
    speaker: 'Led by Dr. Sarah Jenkins, Partner at Silicon Valley Capital'
  },
  {
    time: '11:30 AM — 01:00 PM',
    title: 'Panel: AI Paradigms in Fintech & Financial Infrastructure',
    speaker: 'Featuring CTOs from Stripe, PayPal, and Adyen'
  },
  {
    time: '02:30 PM — 04:30 PM',
    title: 'Fireside Chat: From Seed to IPO in Modern Ecosystems',
    speaker: 'Moderated by Kevin Miller, Tech Journalist at TechCrunch'
  }
];

export const WHO_SHOULD_ATTEND = [
  'Tech Founders and Scaling Executives navigating regional expansion and product-market fit.',
  'Venture Investors and Angel Syndicates seeking premium pipelines and ecosystem interactions.',
  'Corporate Directors exploring partnership integration and digital infrastructure technologies.',
  'Product Managers and Software Architects building robust, high-traffic consumer models.'
];
